Metrics/LineLength:
  Max: 132

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Max: 30

Metrics/AbcSize:
  Max: 30

Metrics/ClassLength:
  Max: 230

Metrics/CyclomaticComplexity:
  Max: 12

Style/FrozenStringLiteralComment:
  Enabled: false
